server:
  port: 8083
  servelet: null
  context-path: /frasesInspira
spring:
  application:
    name: frasesInspira
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate: null
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/frasesInpiracao?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql